# Generated by Django 3.1.4 on 2021-01-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('adress', models.CharField(blank=True, max_length=250, null=True)),
                ('code_posti', models.IntegerField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ph_number', models.IntegerField(blank=True, max_length=250, null=True)),
                ('job', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('N', 'no_diffrence')], default=None, max_length=1)),
            ],
        ),
    ]
