# Generated by Django 3.1.4 on 2021-01-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210101_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='ph_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
