# Generated by Django 3.1.4 on 2021-01-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210101_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='code_posti',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='ph_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
