# Generated by Django 3.1.4 on 2021-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210101_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('No diffrence', 'No_diffrence')], default=None, max_length=20),
        ),
    ]
